// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApCIyME9LBSuptfwMOffJu0m4OJLOQfMY',
    appId: '1:98292228951:web:78ab35d21090fc07639412',
    messagingSenderId: '98292228951',
    projectId: 'fir-crud-9a990',
    authDomain: 'fir-crud-9a990.firebaseapp.com',
    storageBucket: 'fir-crud-9a990.firebasestorage.app',
    measurementId: 'G-KKGBYNQTJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd60mA7MoZCx2Y65DjNi1mNyyb0YzZOxc',
    appId: '1:98292228951:android:0b4bdf97d5ceb0d5639412',
    messagingSenderId: '98292228951',
    projectId: 'fir-crud-9a990',
    storageBucket: 'fir-crud-9a990.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwTAvNc7eI9RLjPJbVViJT7NBenEgDhDA',
    appId: '1:98292228951:ios:0636b9dea804863e639412',
    messagingSenderId: '98292228951',
    projectId: 'fir-crud-9a990',
    storageBucket: 'fir-crud-9a990.firebasestorage.app',
    iosBundleId: 'com.example.brisaSupplyChain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwTAvNc7eI9RLjPJbVViJT7NBenEgDhDA',
    appId: '1:98292228951:ios:0636b9dea804863e639412',
    messagingSenderId: '98292228951',
    projectId: 'fir-crud-9a990',
    storageBucket: 'fir-crud-9a990.firebasestorage.app',
    iosBundleId: 'com.example.brisaSupplyChain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9DVXtuM7fYRaggJHAZ15-oPHXod5eFQY',
    appId: '1:98292228951:web:ffadf1f01182716c639412',
    messagingSenderId: '98292228951',
    projectId: 'fir-crud-9a990',
    authDomain: 'fir-crud-9a990.firebaseapp.com',
    storageBucket: 'fir-crud-9a990.firebasestorage.app',
    measurementId: 'G-BDWLVS0J4B',
  );

}